language: ruby

before_install:
  - gem update --system
  - gem install bundler -v 1.17.3

install:
  - bundler install --path vendor/bundle

cache: bundler
script: make build

deploy:
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: _site
    committer_from_gh: true
    target_branch: gh-pages
    repo: canvascbl/landing
    edge: true
    on:
      branch: master
